name: "Run Chat Completion Request"
description: "Runs a chat completion request test"

inputs:
  api_key:
    description: "API key for authentication"
    required: true
  api_url:
    description: "API URL endpoint"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22.14.0"

    - name: Build atoma-nodes
      shell: bash
      working-directory: interop/nodes
      run: make

    - name: Install dependencies
      shell: bash
      working-directory: interop/runner
      run: npm ci

    - name: run e2e-test
      shell: bash
      env:
        ATOMA_API_KEY: ${{ inputs.api_key }}
        ATOMA_API_URL: ${{ inputs.api_url }}
      working-directory: interop/runner
      run: npm run e2e-test

    - name: Collect Docker logs on failure
      shell: bash
      working-directory: interop
      if: failure()
      run: |
        docker compose logs
