name: "Run Chat Completion Request"
description: "Runs a chat completion request test"

inputs:
  api_key:
    description: "API key for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Make scripts executable
      shell: bash
      working-directory: interop/nodes/scripts
      run: |
        chmod +x deploy.sh
        chmod +x teardown.sh
        chmod +x node_setup.sh
        chmod +x proxy_setup.sh

    - name: Deploy infrastructure
      shell: bash
      working-directory: interop/nodes/scripts
      run: ./deploy.sh

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.14.0"
        cache: "npm"
        cache-dependency-path: interop/runner/package-lock.json

    - name: Build atoma-nodes
      shell: bash
      working-directory: interop/nodes
      run: make

    - name: Install dependencies
      shell: bash
      working-directory: interop/runner
      run: npm ci

    - name: run e2e-test
      shell: bash
      env:
        ATOMA_API_KEY: ${{ inputs.api_key }}
        ATOMA_API_URL: ${{ env.PROXY_IP }}
      working-directory: interop/runner
      run: npm run e2e-test

    - name: Collect Docker logs on failure
      shell: bash
      working-directory: interop/nodes/atoma-node
      if: failure()
      run: |
        echo "=== Atoma Node Logs ==="
        docker compose logs

        echo -e "\n=== Atoma Proxy Logs ==="
        cd ../atoma-proxy
        docker compose logs

    - name: Teardown infrastructure
      shell: bash
      run: ./teardown.sh
