name: "Run Chat Completion Request"
description: "Runs a chat completion request test"

inputs:
  api_key:
    description: "API key for authentication"
    required: true
  api_url:
    description: "API URL endpoint"
    required: true
  sui_config:
    description: "Sui config"
    required: true
  sui_keypair:
    description: "Sui keypair"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Sui Config
      shell: bash
      run: |
        mkdir -p ./sui_config
        echo "${{ inputs.SUI_CONFIG }}" > ./sui_config/client.yaml
        echo "${{ inputs.SUI_KEYPAIR }}" > ./sui_config/sui.keystore

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.14.0"
        cache: "npm"
        cache-dependency-path: interop/runner/package-lock.json

    - name: Build atoma-nodes
      shell: bash
      working-directory: interop/nodes
      run: make

    - name: Install dependencies
      shell: bash
      working-directory: interop/runner
      run: npm ci

    - name: run e2e-test
      shell: bash
      env:
        ATOMA_API_KEY: ${{ inputs.api_key }}
        ATOMA_API_URL: ${{ inputs.api_url }}
      working-directory: interop/runner
      run: npm run e2e-test

    - name: Collect Docker logs on failure
      shell: bash
      working-directory: interop/nodes/atoma-node
      if: failure()
      run: |
        echo "=== Atoma Node Logs ==="
        docker compose logs

        echo -e "\n=== Atoma Proxy Logs ==="
        cd ../atoma-proxy
        docker compose logs
