name: "chat completion request"
description: "Runs a chat completion request with a given model"
inputs:
  api-key:
    description: "The API key to use"
    required: true
  model:
    description: "Which model to use"
    required: false
    default: "meta-llama/Llama-3.3-70B-Instruct"
runs:
  using: "composite"
  steps:
    - name: Run E2E Tests
      uses: atoma-network/e2e-tests@main
      with:
        api_url: ${{ inputs.api_url }}
        api_key: ${{ secrets.api_key }}
