apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  claimName: hf-model-pvc
containers:
  - name: atoma-node
    image: ghcr.io/atoma-network/atoma-node:latest
    volumeMounts:
      - mountPath: /models
        name: model-cache
    env:
      - name: TRANSFORMERS_CACHE
        value: /models
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: ${{secrets.HF_TOKEN}}
            key: token
