# .github/workflows/test-env.yml
name: Dev Environment Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Setup test environment
        run: |
          mkdir -p logs
          cp config.example.toml config.toml
          touch .env
          echo "POSTGRES_DB=atoma" >> .env
          echo "POSTGRES_USER=atoma" >> .env
          echo "POSTGRES_PASSWORD=password123" >> .env

      - name: Start Docker services
        run: |
          docker-compose -f docker-compose.yml up -d atoma-proxy-local postgres-db
          docker-compose -f docker-compose-node.yml up -d atoma-node-non-confidential

      - name: Wait for services
        run: |
          echo "Waiting for services to be ready..."
          sleep 30

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          ATOMA_API_URL: http://localhost:8080
          ATOMA_API_KEY: test-key

      - name: Collect Docker logs on failure
        if: failure()
        run: |
          docker-compose logs
          docker-compose -f docker-compose-node.yml logs
