# .github/workflows/test-env.yml
name: Dev Environment Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Go to interop directory
        run: cd interop

      - name: Build atoma-node
        run: make

      - name: Build atoma-proxy
        run: make

      - name: Go to runner directory
        run: cd runner

      - name: Install dependencies
        run: npm ci

      - name: run e2e-test
        run: npm run e2e-test

      - name: Collect Docker logs on failure
        if: failure()
        run: |
          docker-compose logs
          docker-compose -f docker-compose-node.yml logs
