name: Dev Environment Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    timeout-minutes: 240
    defaults:
      run:
        shell: bash
        working-directory: interop
    steps:
      - name: Checkout test-plans
        uses: actions/checkout@v4

      - name: Run Chat Completion e2e Test
        uses: ./.github/actions/run-chat-completion-request
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          api_key: ${{ secrets.ATOMA_API_KEY }}
          node_config: ${{ secrets.NODE_CONFIG }}
          node_env: ${{ secrets.NODE_ENV }}
          node_local_key: ${{ secrets.NODE_LOCAL_KEY }}
          proxy_config: ${{ secrets.PROXY_CONFIG }}
          proxy_env: ${{ secrets.PROXY_ENV }}
          proxy_local_key: ${{ secrets.PROXY_LOCAL_KEY }}
          sui_aliases: ${{ secrets.SUI_ALIASES }}
