name: Dev Environment Test

# TODO: Remember to change this to be on pushes
on:
  workflow_dispatch:

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    timeout-minutes: 240
    defaults:
      run:
        shell: bash
        working-directory: interop
    steps:
      - name: Checkout test-plans
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Run Chat Completion e2e Test
        uses: ./.github/actions/run-chat-completion-request
        with:
          api_key: ${{ secrets.ATOMA_API_KEY }}
